apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.19.0
        imagePullPolicy: IfNotPresent
        name: nginx
        resources:
          requests:
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "150m"